version: "3.8"
services:
  radar:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - "3000:3000"
    restart: unless-stopped
